### ISSUE TITLE
 170 -- unable to write pixel cache `/tmp/magick-793213zZ04aF8PFiN

### ISSUE THREAD

**Issue by sunosv** [LycheeOrg/Lychee#846]
This is probably a bug.

No matter I put lychee on linux or Windows , When I upload the same video,It will fail.
Probably because the  Audio is  pcm_s16be ???
I found  that except the audio format pcm can't upload ,Other videos are OK
The video is from Sony A6400.

### **Video info**
**Metadata:
    major_brand     : XAVC
    minor_version   : 16785407
    compatible_brands: XAVCmp42iso2
    creation_time   : 2020-06-16T00:37:20.000000Z
  Duration: 00:00:11.04, start: 0.000000, bitrate: 60799 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709/bt709/iec61966-2-4), 1920x1080 [SAR 1:1 DAR 16:9], 55848 kb/s, 100 fps, 100 tbr, 100k tbn, 200 tbc (default)
    Metadata:
      creation_time   : 2020-06-16T00:37:20.000000Z
      handler_name    : Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(und): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2020-06-16T00:37:20.000000Z
      handler_name    : Sound Media Handler
    Stream #0:2(und): Data: none (rtmd / 0x646D7472), 819 kb/s (default)
    Metadata:
      creation_time   : 2020-06-16T00:37:20.000000Z
      handler_name    : Timed Metadata Media Handler
      timecode        : 02:02:08:16**

lychee on linux logs:

**2021-01-01 21:31:48 -- notice  -- App\Metadata\GitHubFunctions::__construct -- 49 -- file_get_contents(/www/wwwroot/lychee/.git/HEAD): failed to open stream: No such file or directory
    2021-01-01 20:01:02 -- error   -- App\Image\ImagickHandler::crop -- 170 -- unable to write pixel cache `/tmp/magick-793213zZ04aF8PFiN': No space left on device @ error/cache.c/WritePixelCachePixels/5984
    2021-01-01 19:57:47 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 617 -- Photo URL is 695081231bc4813befa584f4bfb06112.MP4
    2021-01-01 19:40:33 -- error   -- App\Image\ImagickHandler::crop -- 170 -- unable to write pixel cache `/tmp/magick-23289EEKGGuu3Coue': No space left on device @ error/cache.c/WritePixelCachePixels/5984
    2021-01-01 19:37:30 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 617 -- Photo URL is 38f361ac7a8ee14370ee1af45cafd584.MP4
    2021-01-01 19:13:09 -- error   -- App\Image\ImagickHandler::crop -- 170 -- unable to write pixel cache `/tmp/magick-10520bgqgwTxXi7l3': No space left on device @ error/cache.c/WritePixelCachePixels/5984**

` Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (release):        4.0.8
    DB Version:                      4.0.8
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          39120M
    Max post size:                   49020M
    MySQL Version:                   5.7.32-log
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      bundled (2.1.0 compatible)

    Config Information
    --------------
    version:                         040008
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              title
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            简体中文
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 1
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            1
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0`

**Comment by d7415** [comment]
> No space left on device

How much space is available on /tmp? Or, more specifically, how much was there when that error was generated?

**Comment by sunosv** [comment]
> > No space left on device
> 
> How much space is available on /tmp? Or, more specifically, how much was there when that error was generated?



> > No space left on device
> 
> How much space is available on /tmp? Or, more specifically, how much was there when that error was generated?

Is it because the video format is not supported? Maybe mp4 container format dose not support raw pcm audio When ffmpeg deal with the video file?

This video is mp4 container, But audio is PCM .
When I convert the audio to aac, the video will upload successfully

https://stackoverflow.com/questions/17651975/unable-to-store-pcm-audio-in-mp4-container-file

video details

**General
Format : XAVC
Codec ID : XAVC (XAVC/mp42/iso2)
File size : 44.0 MiB
Duration : 6 s 240 ms
Overall bit rate mode : Variable
Overall bit rate : 59.2 Mb/s
Encoded date : UTC 2020-05-24 23:04:00
Tagged date : UTC 2020-05-24 23:04:00

Video
ID : 1
Format : AVC
Format/Info : Advanced Video Codec
Format profile : High@L5.1
Format settings : CABAC / 2 Ref Frames
Format settings, CABAC : Yes
Format settings, Reference frames : 2 frames
Codec ID : avc1
Codec ID/Info : Advanced Video Coding
Duration : 6 s 240 ms
Bit rate mode : Variable
Bit rate : 57.3 Mb/s
Maximum bit rate : 60.0 Mb/s
Width : 3 840 pixels
Height : 2 160 pixels
Display aspect ratio : 16:9
Frame rate mode : Constant
Frame rate : 25.000 FPS
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Progressive
Bits/(Pixel*Frame) : 0.276
Stream size : 42.6 MiB (97%)
Encoded date : UTC 2020-05-24 23:04:00
Tagged date : UTC 2020-05-24 23:04:00
Color range : Full
Codec configuration box : avcC

Audio
ID : 2
Format : PCM
Format settings : Big / Signed
Codec ID : twos
Duration : 6 s 240 ms
Bit rate mode : Constant
Bit rate : 1 536 kb/s
Channel(s) : 2 channels
Sampling rate : 48.0 kHz
Bit depth : 16 bits
Stream size : 1.14 MiB (3%)
Encoded date : UTC 2020-05-24 23:04:00
Tagged date : UTC 2020-05-24 23:04:00**

**Comment by kamil4** [comment]
Just as in #844, you failed to provide the requested information, which prevents us from being able to help you. In this case @d7415 clearly requested the following:

> How much space is available on /tmp? Or, more specifically, how much was there when that error was generated?

Please answer that question first. If it doesn't look like this may have been the issue, please upload the problematic video file to some file sharing service and send us the URL so that we can properly investigate what's going on here.

**Comment by sunosv** [comment]
> > No space left on device
> 
> How much space is available on /tmp? Or, more specifically, how much was there when that error was generated?

I don't know well about linux,  But there is a temp in the root directory "/"  .It has 11GB capacity.

**Comment by d7415** [comment]
> > How much space is available on /tmp? Or, more specifically, how much was there when that error was generated?
> 
> I don't know well about linux, But there is a temp in the root directory "/" .It has 11GB capacity.

`df -h /tmp` should be the easiest option.

**Comment by sunosv** [comment]
> > > How much space is available on /tmp? Or, more specifically, how much was there when that error was generated?
> > 
> > 
> > I don't know well about linux, But there is a temp in the root directory "/" .It has 11GB capacity.
> 
> `df -h /tmp` should be the easiest option.

/dev/mapper/cl-root   17G  7.8G  9.3G   46% /
It has space.

**Comment by kamil4** [comment]
Can you make the file available for us to test with? Thanks!

**Comment by kamil4** [comment]
This looks similar to https://github.com/LycheeOrg/Lychee/issues/766. But that bug is fixed, and it wasn't being triggered on upload anyway...

**Comment by sunosv** [comment]
I really don't know what went wrong.It still can't upload in my win environment.

lychee on Windows logs：
2021-01-07 16:13:23 -- error -- App\Image\ImagickHandler::crop -- 170 -- UnableToOpenBlob 'C:/Users/ADMINI~1/AppData/Local/Temp/magick-32929igvO8DVgoA2.pam': No such file or directory @ error/blob.c/OpenBlob/3315

And,I want to see the difference between linux and windows. I have tried to upload the video in my linux environment.

the video file size is only 44MB and It took a long time, still failed.
lychee on linux logs:

2021-01-07 16:23:13 -- error -- App\Image\ImagickHandler::crop -- 170 -- unable to write pixel cache `/tmp/magick-12328XNdv7pP3CKJP': No space left on device @ error/cache.c/WritePixelCachePixels/5984
2021-01-07 16:21:02 -- notice -- App\ModelFunctions\PhotoFunctions::createThumb -- 617 -- Photo URL is f41709fb6b4917773b0cc106a8001330.MP4
2021-01-07 16:20:50 -- notice -- App\Metadata\GitHubFunctions::__construct -- 49 -- file_get_contents(/www/wwwroot/lychee/.git/HEAD): failed to open stream: No such file or directory

And Another interesting thing is that the temp space has run out, When uploading the video, although It has 9.3GB.

This is the change of space ,While Uploading the video.

**[root@localhost ~]# df -h /tmp
Filesystem Size Used Avail Use% Mounted on
/dev/mapper/cl-root 17G 8.8G 8.3G 52% /

[root@localhost ~]# df -h /tmp
Filesystem Size Used Avail Use% Mounted on
/dev/mapper/cl-root 17G 9.8G 7.3G 58% /

/dev/mapper/cl-root 17G 11G 6.4G 63% /

/dev/mapper/cl-root 17G 12G 5.7G 67% /

/dev/mapper/cl-root 17G 16G 1.9G 89% /

/dev/mapper/cl-root 17G 16G 1.6G 92% /

/dev/mapper/cl-root 17G 16G 1.3G 93% /

/dev/mapper/cl-root 17G 16G 1.2G 94% /

/dev/mapper/cl-root 17G 7.8G 9.3G 46% /

#844 
@kamil4


>

**Comment by sunosv** [comment]
> Can you make the file available for us to test with? Thanks!

It's the same video file.

**Comment by kamil4** [comment]
Are you uploading from a Windows machine? What web browser? I think that may be responsible for the difference we're seeing... I have a Windows 7 VM somewhere that I can try to reproduce this on (client-side only though; I'm not brave enough to try running the server on Windows...).

**Comment by sunosv** [comment]
> Are you uploading from a Windows machine? What web browser? I think that may be responsible for the difference we're seeing... I have a Windows 7 VM somewhere that I can try to reproduce this on (client-side only though; I'm not brave enough to try running the server on Windows...).

I am using Goolge Chrome to uoload on windows10

**Comment by kamil4** [comment]
OK, I found the problem. I couldn't reproduce it at first because in my configuration `has_exiftool = 1`, which I didn't think would matter, but it turns out it does.

So to fix this, you can either install exiftool or override the content of the file `Lychee/app/ModelFunctions/PhotoFunctions.php` with https://raw.githubusercontent.com/LycheeOrg/Lychee/fix-846/app/ModelFunctions/PhotoFunctions.php

Mind you, for this to work, you will also need to have installed the fix from https://github.com/LycheeOrg/Lychee/issues/844#issuecomment-755543332

**Comment by sunosv** [comment]
> OK, I found the problem. I couldn't reproduce it at first because in my configuration `has_exiftool = 1`, which I didn't think would matter, but it turns out it does.
> 
> So to fix this, you can either install exiftool or override the content of the file `Lychee/app/ModelFunctions/PhotoFunctions.php` with https://raw.githubusercontent.com/LycheeOrg/Lychee/fix-846/app/ModelFunctions/PhotoFunctions.php
> 
> Mind you, for this to work, you will also need to have installed the fix from [#844 (comment)](https://github.com/LycheeOrg/Lychee/issues/844#issuecomment-755543332)

Wow！ It worked. Thank you! Thank you! Thank you! very much!!

**Comment by sunosv** [comment]
> OK, I found the problem. I couldn't reproduce it at first because in my configuration `has_exiftool = 1`, which I didn't think would matter, but it turns out it does.
> 
> So to fix this, you can either install exiftool or override the content of the file `Lychee/app/ModelFunctions/PhotoFunctions.php` with https://raw.githubusercontent.com/LycheeOrg/Lychee/fix-846/app/ModelFunctions/PhotoFunctions.php
> 
> Mind you, for this to work, you will also need to have installed the fix from [#844 (comment)](https://github.com/LycheeOrg/Lychee/issues/844#issuecomment-755543332)

Do you know how to install ExifTool on Windows for lychee?
